name: Deploy to GitHub Pages

# tell GH to grant write perms to contents & pages
permissions:
  contents: write      # allow pushing commits
  pages: write         # allow updating Pages branch

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./       # folder to publish
          publish_branch: gh-pages
